version: '3.8'

services:
  nginx:
    container_name: company-versioning-www
    image: nginx:1.16-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './app/api/public:/var/www/app/public:ro'
      - './app/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php

  php:
    container_name: company-versioning-php
    depends_on:
      - db
    build:
      context: ./app
    ports:
      - '9000:9000'
    volumes:
      - './app/api:/var/www/app'

  db:
    container_name: company-versioning-db
    image: mariadb:10.11.2
    restart: on-failure
    command: [ '--default-authentication-plugin=mysql_native_password' ]
    volumes:
      - 'mariabd_data:/var/lib/mysql'
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: symfony
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password
    ports:
      - '3306:3306'

  front:
    container_name: company-versioning-front
    build:
      context: ./front
      target: dev
    depends_on:
      - nginx
    volumes:
      - './front:/app'
      - '/app/node_modules'
    ports:
      - '3000:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

volumes:
  mariabd_data:
    driver: local
