version: '3.8'

services:
  nginx:
    container_name: company-versioning-www
    image: nginx:1.16-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './api/app/public:/var/www/app/public:ro'
      - './api/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php

  php:
    container_name: company-versioning-php
    depends_on:
      - db
    build:
      context: ./api
    ports:
      - '9000:9000'
    volumes:
      - './api/app:/var/www/app'

  db:
    container_name: company-versioning-db
    image: mariadb:10.11
    restart: always
    command: [ '--default-authentication-plugin=mysql_native_password' ]
    volumes:
      - 'mariabd_data:/var/lib/mysql'
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: symfony
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password

volumes:
  mariabd_data:
    driver: local
