fos_rest:
    routing_loader: false
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: [ json, html ], fallback_format: json }
    exception:
        enabled: true
