name: Check vulnerabilities

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
        name: Checkout
        with:
          persist-credentials: false

      - name: Symfony security checker
        id: 'security-check'
        continue-on-error: true
        uses: 'symfonycorp/security-checker-action@v4'
        with:
          lock: ./app/api/composer.lock

      - name: Display the vulnerabilities as JSON
        if: steps.security-check.outcome == 'failure'
        run: echo ${{ steps.security-check.outputs.vulns }}
