name: Web APP CI

on:
  push

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v3'
        name: Checkout
        with:
          persist-credentials: false

      - name: Setup Node
        uses: 'actions/setup-node@v3'
        with:
          node-version: 19.x
          cache: 'yarn'
          cache-dependency-path: './front/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: './front/'

      - name: Lint
        run: yarn lint
        working-directory: './front/'

      - name: Code standard check
        run: yarn prettier-check
        working-directory: './front/'
      # todo: add tests
      - name: Build
        run: yarn build:ci
        working-directory: './front/'

      - name: Setup Pages
        uses: 'actions/configure-pages@v3'

      - name: Build GitHub Page
        uses: 'actions/jekyll-build-pages@v1'
        with:
          source: './front/dist/'
          destination: './_site'

      - name: Upload artifact
        uses: 'actions/upload-pages-artifact@v1'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: 'actions/deploy-pages@v2'
