name: Web APP CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v3'
        name: Checkout
        with:
          persist-credentials: false

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: 'actions/cache@v1'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v3'
        with:
          node-version: 19.x
          cache: 'yarn'
          cache-dependency-path: './front/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Code standard check
        run: yarn prettier-check

      - name: Build
        run: yarn build:ci

      # todo: add tests
      # todo add deploy gh-pages only when push main branch
