name: Web APP CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v3'
        name: Checkout
        with:
          persist-credentials: false

      - name: Setup Node
        uses: 'actions/setup-node@v3'
        with:
          node-version: 19.x
          cache: 'yarn'
          cache-dependency-path: './front/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: './front/'

      - name: Lint
        run: yarn lint
        working-directory: './front/'

      - name: Code standard check
        run: yarn prettier-check
        working-directory: './front/'

      - name: Build
        run: yarn build:ci
        working-directory: './front/'

      # todo: add tests
      # todo add deploy gh-pages only when push main branch
